version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.1.7
      - image: cimg/mysql:8.0
        environment:
          MYSQL_DATABASE: testing
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
    environment:
      APP_ENV: testing
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: testing
      DB_USERNAME: root

    steps:
      - checkout
      - run:
          name: install mysql
          command: |
            sudo apt-get update
            sudo apt-get install default-mysql-client

      - run:
          name: MySQL が準備できるまで待機
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1

      - restore_cache:
          key: composer-v1-{{ checksum "composer.lock" }}

      - run: composer install -n --prefer-dist

      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      - run:
          name: php test
          command: vendor/bin/phpunit
