version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.1.7

    steps:
      - checkout
      - run:
          name: composer install
          command: docker run --rm -u "$(id -u):$(id -g)" -v $(pwd):/var/www/html -w /var/www/html laravelsail/php81-composer:latest composer install --ignore-platform-reqs
